### ISSUE TITLE
导出按钮无反应

### ISSUE THREAD

**Issue by Pengwei-Chen-1** [LancelotLewis/local-kitymind#1]
Hi,
    本地环境：win7, chrome Version 57.0.2987.133 (64-bit)
    导入功能没问题，正常编辑也可以，但是点击右上角的几个导出按钮无反应，无法导出。这样的话就没法保存了。。。。
   如有时间，还请帮忙看下这个问题，谢谢。

**Comment by lancelot-lewis** [comment]
@guduchina chrome下确实不行，我是用360极速浏览器没问题。chrome这边可能是事件兼容性的问题，我有时间再具体研究，到时候会通知你，感谢反馈

**Comment by Pengwei-Chen-1** [comment]
我实在是找不到其他的方法了。。。。。
高版本的chrome下确实不行，不过52版本的chrome貌似可以。
我改了下导出的方法，创建了一个a链接，点击可下载文件，多了一步。


`// 由于chrome较高版本中无法实现自动触发event，所以改用以下方法进行导出
var fileName = $('#node_text1').text()+'.'+type;
var aLink = document.createElement('a');
// 点击后自动删除当前a标签
aLink.onclick = function() {
    $(this).remove();
};

var node = document.createTextNode(fileName);
aLink.appendChild(node);
var blob = new Blob([content]);
aLink.download = fileName;
aLink.href = URL.createObjectURL(blob);
$('.editor-title').append(aLink);`

**Comment by lancelot-lewis** [comment]
@guduchina chrome的机制是阻止代码触发的页面点击事件，据说是为了防止广告，之前听说一个办法是设置setTimeout延时执行代码模拟的点击事件。

**Comment by lancelot-lewis** [comment]
@guduchina 使用了很奇葩的方式hack了chrome浏览器的限制，仅供参考
