### ISSUE TITLE
大神，你好

### ISSUE THREAD

**Issue by M3PWmE** [LancelotLewis/local-kitymind#2]
大神，你好，很感谢你的辛勤劳作，在使用中有一些问题。为什么没有自动保存功能啊？有时候导出按钮不能点击，能不能优化一下？能做成chrome的应用吗？

**Comment by lancelot-lewis** [comment]
@legendslov 
- 自动保存需要依托于存储介质，使用localStorage倒是一个解决办法，会考虑加上去。
- 导出按钮的功能是使用模拟点击a标签实现的，由于部分浏览器会拦截模拟点击请求，所以改成了hover到按钮上才 生成导出文件的数据，所以可能在快速移动到按钮就点击的情况下是会出现导出失败的。解决办法就移动到下载按钮之后，等待一会再点击应该是没问题的（其实也可以监听内容的改变动态生成导出数据，只是我觉得这样消耗性能，才选择折衷的做法）
- chrome应用就暂时不考虑了
