### ISSUE TITLE
关于你脑图的二次开发想向您请教

### ISSUE THREAD

**Issue by Alice-z** [LancelotLewis/local-kitymind#3]
您好，请问您这个二次开发是不是clone那个editor 然后进行修改后 打包就行了呢？

**Comment by lancelot-lewis** [comment]
@Alice-z 是的，你可以clone到本地试试

**Comment by Alice-z** [comment]
二次开发 需要对ng 和seajs熟悉吗？

**Comment by lancelot-lewis** [comment]
@Alice-z 需要深度定制开发的话，要改动里面的组件和模块，是需要有相应知识的
